### ISSUE TITLE
Add a *debug-on-failure* special var

### ISSUE THREAD

**Issue by EuAndreh** [fukamachi/prove#11]
As already [mentioned](https://github.com/fukamachi/fast-http/pull/12), it would be useful to know when a test fails, so one could exit the running test with an (unix) exit code different from 0.

**Comment by fukamachi** [comment]
I don't think this is useful so much because it's not actually _debug_. And I'm not sure it's a good manner that stopping all following tests when a test failed.

**Comment by EuAndreh** [comment]
Well, I believe that you're right. That wouldn't be that useful, actually.

Thanks =]
