### ISSUE TITLE
Reference to +gray+ broken?

### ISSUE THREAD

**Issue by quicklisp** [fukamachi/prove#27]
http://report.quicklisp.org/2016-08-03/failure-report/prove.html#prove-asdf has a log - this affects many projects.

    Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1003327673}>: Error finding package for symbol "+GREY+":
     The name "CL-COLORS" does not designate any package.

**Comment by mohsenil85** [comment]
fixed in #28

**Comment by fukamachi** [comment]
Merged @mohsenil85's PR.

**Comment by quicklisp** [comment]
I see no change in the failure even after this update.

**Comment by fukamachi** [comment]
I made another change in https://github.com/fukamachi/prove/commit/489e4d0f4140998928cd5a8717f3e826c4d325d5.

**Comment by fukamachi** [comment]
@quicklisp Is it still broken?

**Comment by quicklisp** [comment]
Everything builds fine for me now, thanks.

**Comment by fukamachi** [comment]
Great. Thank you for reporting :)
