### ISSUE TITLE
'skip' doesn't work

### ISSUE THREAD

**Issue by fourier** [fukamachi/prove#32]
The next test if the 'skip' is set to say 1 is still marked as failed.
```
# Testing read-offsets
    ok 1 - check simple table with values < 2^31
    ok 2 - skip TODO: reimplement large offsets handling and enable this test
2147483648
    not ok 3
    #    got: #<END-OF-FILE {10077A7843}>
    #    expected: #(545404204 2013771743)
```
    (skip 1 "TODO: reimplement large offsets handling and enable this test")
    (is got tested)
```
- the test with "is" is not skipped and marked as fail, see log above

**Comment by fukamachi** [comment]
It's a wrong way to use `skip`. `skip` is like `pass` but it indicates the test as "skip" at the comment line.

```common-lisp
(if *some-frag*
    (skip 1 "TODO: reimplement large offsets handling and enable this test")
    (is got tested))
```

**Comment by fourier** [comment]
Ok thanks, it is more clear now, maybe it is better to update the documentation to state more clear what it is used for.
