### ISSUE TITLE
In asdf 3.2, only make-operation can create an operation instance

### ISSUE THREAD

**Issue by fare** [fukamachi/prove#35]
prove/src/asdf.lisp uses `(make-instance 'asdf:load-source-op)` but this is not correct,
and this is disallowed in asdf 3.2 (so it can rely on hash-consing for equality testing and enable future developments). Can you instead use `(asdf:make-operation 'asdf:load-source-op)` or even, in this context, just `'asdf:load-source-op` ?

**Comment by easye** [comment]
Removing the (now) unnecessary pull request <https://github.com/fukamachi/prove/pull/34>
